name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-prod:
    if: github.ref == 'refs/heads/main'
    uses: your-org/workflow-templates/.github/workflows/build-and-push.yml@main
    with:
      image_name: 'eks-agent'
      version_prefix: ''
    permissions:
      contents: write
      packages: write

